### ISSUE TITLE
Which article do you refer to？

### ISSUE THREAD

**Issue by zhangzy6** [alexbox23/210A-project#1]
I am very interested in this topic. Can you provide the source of the dataset？Thanks very much.

**Comment by alexbox23** [comment]
Hi, this was for a graduate course and the data was generated by the professor using a waveguide dispersion simulator (VPIphotonics). I uploaded the slide deck for the project, which contains the parameters of the simulation. See Team6_Alex_Matthew_Presentation.pdf in the latest commit.

**Comment by guoyu666** [comment]
Thanks!
